### ISSUE TITLE
pio: allwinner mem-mapped gpio.Out is 5x slower than gpio.In

### ISSUE THREAD

**Issue by tve** [maruel/dlibox#4]
I have the feeling that setFunction does not check whether the pin is already an output and makes it an output each time?

Results of pin-perf on CHIP:

```
Testing gpio output speed
  1.2us per Out()
Testing sysfs output speed
  14.4us per Out()
Testing gpio input speed
  0.2us per In()
Testing sysfs input speed
  9.3us per In()
Testing gpio out+in speed
  1.1us per In()
Testing sysfs out+in speed
  26.7us per In()
```

**Comment by maruel** [comment]
Indeed, there was a bug.

**Comment by tve** [comment]
The performance of Out() is still an issue:

```
Testing gpio output speed
  2.0us per Out()
Testing gpio input speed
  0.1us per Read()
Testing gpio out+in speed
  1.1us per Out()+Read()
```

What I'm seeing in the allwinner case is that because Out() calls p.setFunction there are a total of 4 I/O reads (1 in p.function called twice, 2 in p.setFunction) and 3 I/O writes (2 in setFunction and 1 in Out). I wonder whether all these I/O register reads & writes are slowing it down...

**Comment by tve** [comment]
Trying some thing out, I have the feeling it's mostly due to the slew of function calls involved in Out(). I added a function field to Pin and saved the last function set in setFunction and then skipped the setting if the requested function is the same as the current function (similar to what the sysfs driver does). The result:

```
Testing gpio output speed
  0.5us per Out()
Testing gpio input speed
  0.1us per Read()
Testing gpio out+in speed
  0.4us per Out()+Read()
```

Looks better! (I don't have an explanation for why Out+Read is faster than just Out...)

**Comment by tve** [comment]
Would you mind reopening this issue? Never mind, I have a fix queued-up for a PR once the new repo exists.

**Comment by maruel** [comment]
Let's close it here.
