### ISSUE TITLE
pio/protocols: comments

### ISSUE THREAD

**Issue by tve** [maruel/dlibox#7]
## Conn

It would be nice to comment why there's no io.Reader

I don't understand the comment about the UART requiring the two buffers to have the same length, that doesn't make any sense to me.

You have "Warning: 'write' is the first argument." for Tx, isn't that an indication that the arguments should be swapped?
## UART

I find the use of Conn really awkward. When reading, how do I know how many bytes I got out of the uart buffer? If I use Tx how do I know how many bytes fit into the outgoing buffer?

How about interrupts? How can I use the UART protocol to interface to a UART that has an RX interrupt, or both RX and TX interrupts?

**Comment by tve** [comment]
## Pins

I would appreciate a write-up about pin numbers, names, and functions in a broad sense. I think we understand that manufacturers assign names to pins and we try to maintain those in PIO so applications can get a handle onto a pin that has a certain name. Numbers are mysterious, however.

Well, names are not entirely obvious either: something PIO doesn't currently handle is a many-to-many relationship between names and pins. Clearly many pins have more than one name and function, but it is also true that a name/function can be mapped to more than one pin. (Maybe add `AllByName(name string) []PinIO` and `AllByFunction()`?) Or does PIO require that names be unique?

For boards (hosts?) you have a notion of a header, which refers to something pretty unambiguous. At the processor level the same unambiguous notion is not clearly exposed is it? And then there's the Linux/sysfs level where gpio pins in particular get assigned numbers that mostly have a non-obvious relationship to any processor or header numbering or naming. I don't know whether Windows, MacOS, FreeBSD, Plan9, etc have a similar notion or whether that's just a Linux thing. I think writing up a page that lays out what pin numbers are and what they are not would be both educative and would help clarify whether there is a portable notion here.

I'm actually missing having an enumeration of pins in the pins package. The ByXxx() functions are in gpio. But that implicitly assumes that all pins are usable as gpio pins, which is not true. (E.g. R8 microphone, speaker, touch screen pins don't have gpio capability.) The All() function also states "This list excludes non-GPIO pins like GROUND, V3_3, etc." which is fine from a gpio perspective, but doesn't support other uses such as displaying the layout of a header. Mhh, I don't see headers anywhere in protocols yet I think that is also a valuable concept.

It seems to me that you have done a ton of reorg this past week and while that's great, perhaps a good next step would be to write up a one-two page explanation. Specifically: how do processor pins, header pins, and "operating system pins" (e.g. sysfs) come together to form the universe of pins available and how are they then made discoverable and usable by applications?

**Comment by tve** [comment]
## Conn vs RegFile

I was thinking about how I would write a one-wire driver and it struck me that while it could fit into the Conn abstraction I also believe that pio is missing a higher-level abstraction, which is that of a register file. What I mean by that is the registers in a peripheral chip and operations to read and write these registers. I don't mean to model the registers by name or such but to provide an interface that has ReadRegs and WriteRegs. There are very few chips I know that don't have registers internally and pretty much all drivers I've seen boil down to reading and writing those registers. So it seems natural to provide an abstraction to do that. Unless you think that every device driver should define its own ReadReg and WriteReg functions.

I think the difficulty is that on a given bus there may be multiple ways to address registers and to perform the read and write operations, although as far as I can tell there really is a 90%+ model.

Thought experiment: suppose you remove Conn and replace it with:

```
type RegFile interface {
  // ReadRegs reads n bytes from the device's registers at or starting at address addr.
  ReadRegs(addr, n int) ([]byte, error)
  // WriteRegs writes the data bytes to the device's registers at or starting at address addr
  WriteRegs(addr int, data []byte) error
}
```

What are you going to be missing, what is not going to work? I don't believe it takes anything away from one-wire, uart, or I2C. I know there are some SPI devices where the simultaneous TX&RX is required and the TX is not just a register address (although arguably the addr int could be used to TX up to 4 bytes). So perhaps the Tx in Conn is still of value, but it seems to me that if RegFile was provided then 90%+ of the library use would use ReadReg and WriteReg and not Tx.

**Comment by maruel** [comment]
For the first comment:
- I agree about UART. This interface is more of an after thought. I unexported it in the meantime.
- Conn expects a full or half duplex interface but assumes it to be the master. The assumption about being the master of a communication channel is quite pervasive; which means io.Reader is normally not directly applicable. I suspect using a connection as a slave will require a totally different interface.
- I removed the warning in protocols.Conn about write being the first argument.

**Comment by maruel** [comment]
For the second comment:
- The library currently assume each gpio has one canonical name. I agree this can be confusing but at the same time, it's less confusing as there's no aliasing.
- I felt headers is more of a host than a protocol thing, hence I've put it in host/headers.
- I added protocols/analog but it's half baked and no pin implement it at the moment.
- gpio.All() and eventually analog.All() fit the need for enumeration, as gpio.Functional().
- I use the pin numbers as represented by sysfs gpio, which exposes the numbering as the actual kernel driver does. This should match. If you look up by name, it should be unambiguous, e.g. "PL3". You can also use headers.All()["P1"][2][1] to refer to a specific pin by its header. Maybe I should keep it 1D instead of 2D (?)
- The concept of non-gpio/non-analog pins like GROUND, V3_3 is only useful when in the context of headers. This is why they are only exposed in this way.
- I'll definitely have to write more doc as things settle.

**Comment by maruel** [comment]
For the third comment:
- WriteRegs() is tricky; on how many bytes should the register be represented? Big or little endian? To work, there's a few configuration knobs needed.
- What an interface buys you vs the concrete i2c.Dev implementation? What do you imagine would accept the interface? Up to now, all device drivers communicating over I²C use [i2c.Dev](https://godoc.org/github.com/maruel/dlibox/go/pio/protocols/i2c#Dev). For devices supporting both SPI and I²C, they generally have very special protocol differences, like [bme280.go](https://github.com/maruel/dlibox/blob/master/go/pio/devices/bme280/bme280.go#L248), so generalizing is non trivial AFAIK.
- To be clear, I'm open to more versatile implementation. I just haven't happened to need it yet as I didn't trigger the "2 implementations need it" yet.

**Comment by tve** [comment]
So ReadRegs and WriteRegs was intended to transfer one or several bytes to/from a register and leave it up to the driver to determine what that means. Many devices seem to have a notion of auto-increment where you can read or write consecutive registers. Some devices I've seen have a FIFO and you can read/write multiple fifo entries by reading/writing multiple bytes to the fifo register.
I think I should tally up some devices to see whether there are 2-3 modes that cover the 90% or not.

**Comment by tve** [comment]
> I'll definitely have to write more doc as things settle.
> I recommend writing docs before things settle. If they're hard to write then things are probably not right yet. I often write docs and as I finish a paragraph I wonder who other than me is going to understand that. Then rewrite it in a way that it's shorter and easier, i.e. changing the functionality, and then I go back and try to implement what I wrote. I find this to be a good iterative loop for a public interface.

Something that is not clear to me is how fixed sysfs gpio pin numbers are on a given "platform". I know that for CHIP the numbers for the XIO gpios, which are really on an I2C extender chip, changed between kernel 4.3 and 4.4. They said that this was an upstream kernel change out of their control. I don't know whether this is routine or an exceptional case.

**Comment by maruel** [comment]
Closing it here, please file again the bits still relevant.
